# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory to /app
WORKDIR /app

# Copy the contents of the local source directory to the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Define environment variable
ENV DATABASE_URL="sqlite:///mydatabase.db"
# Run the command to execute the tests
CMD ["python", "-m", "pytest", "tests/tests.py", "-sv"]
